// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package agent

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_Agentrun_2_list)(nil)

type _Agentrun_2_list struct {
	list *[]string
}

func (x *_Agentrun_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_Agentrun_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_Agentrun_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_Agentrun_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_Agentrun_2_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message Agentrun at list field Responses as it is not of Message kind"))
}

func (x *_Agentrun_2_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_Agentrun_2_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_Agentrun_2_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_Agentrun_3_list)(nil)

type _Agentrun_3_list struct {
	list *[]string
}

func (x *_Agentrun_3_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_Agentrun_3_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_Agentrun_3_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_Agentrun_3_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_Agentrun_3_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message Agentrun at list field Functioncalls as it is not of Message kind"))
}

func (x *_Agentrun_3_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_Agentrun_3_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_Agentrun_3_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_Agentrun_4_list)(nil)

type _Agentrun_4_list struct {
	list *[]string
}

func (x *_Agentrun_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_Agentrun_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_Agentrun_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_Agentrun_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_Agentrun_4_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message Agentrun at list field Functionresults as it is not of Message kind"))
}

func (x *_Agentrun_4_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_Agentrun_4_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_Agentrun_4_list) IsValid() bool {
	return x.list != nil
}

var (
	md_Agentrun                 protoreflect.MessageDescriptor
	fd_Agentrun_query           protoreflect.FieldDescriptor
	fd_Agentrun_responses       protoreflect.FieldDescriptor
	fd_Agentrun_functioncalls   protoreflect.FieldDescriptor
	fd_Agentrun_functionresults protoreflect.FieldDescriptor
	fd_Agentrun_isfinished      protoreflect.FieldDescriptor
	fd_Agentrun_id              protoreflect.FieldDescriptor
)

func init() {
	file_agent_agent_agentrun_proto_init()
	md_Agentrun = File_agent_agent_agentrun_proto.Messages().ByName("Agentrun")
	fd_Agentrun_query = md_Agentrun.Fields().ByName("query")
	fd_Agentrun_responses = md_Agentrun.Fields().ByName("responses")
	fd_Agentrun_functioncalls = md_Agentrun.Fields().ByName("functioncalls")
	fd_Agentrun_functionresults = md_Agentrun.Fields().ByName("functionresults")
	fd_Agentrun_isfinished = md_Agentrun.Fields().ByName("isfinished")
	fd_Agentrun_id = md_Agentrun.Fields().ByName("id")
}

var _ protoreflect.Message = (*fastReflection_Agentrun)(nil)

type fastReflection_Agentrun Agentrun

func (x *Agentrun) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Agentrun)(x)
}

func (x *Agentrun) slowProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_agentrun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Agentrun_messageType fastReflection_Agentrun_messageType
var _ protoreflect.MessageType = fastReflection_Agentrun_messageType{}

type fastReflection_Agentrun_messageType struct{}

func (x fastReflection_Agentrun_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Agentrun)(nil)
}
func (x fastReflection_Agentrun_messageType) New() protoreflect.Message {
	return new(fastReflection_Agentrun)
}
func (x fastReflection_Agentrun_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Agentrun
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Agentrun) Descriptor() protoreflect.MessageDescriptor {
	return md_Agentrun
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Agentrun) Type() protoreflect.MessageType {
	return _fastReflection_Agentrun_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Agentrun) New() protoreflect.Message {
	return new(fastReflection_Agentrun)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Agentrun) Interface() protoreflect.ProtoMessage {
	return (*Agentrun)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Agentrun) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Query != "" {
		value := protoreflect.ValueOfString(x.Query)
		if !f(fd_Agentrun_query, value) {
			return
		}
	}
	if len(x.Responses) != 0 {
		value := protoreflect.ValueOfList(&_Agentrun_2_list{list: &x.Responses})
		if !f(fd_Agentrun_responses, value) {
			return
		}
	}
	if len(x.Functioncalls) != 0 {
		value := protoreflect.ValueOfList(&_Agentrun_3_list{list: &x.Functioncalls})
		if !f(fd_Agentrun_functioncalls, value) {
			return
		}
	}
	if len(x.Functionresults) != 0 {
		value := protoreflect.ValueOfList(&_Agentrun_4_list{list: &x.Functionresults})
		if !f(fd_Agentrun_functionresults, value) {
			return
		}
	}
	if x.Isfinished != false {
		value := protoreflect.ValueOfBool(x.Isfinished)
		if !f(fd_Agentrun_isfinished, value) {
			return
		}
	}
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Agentrun_id, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Agentrun) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "agent.agent.Agentrun.query":
		return x.Query != ""
	case "agent.agent.Agentrun.responses":
		return len(x.Responses) != 0
	case "agent.agent.Agentrun.functioncalls":
		return len(x.Functioncalls) != 0
	case "agent.agent.Agentrun.functionresults":
		return len(x.Functionresults) != 0
	case "agent.agent.Agentrun.isfinished":
		return x.Isfinished != false
	case "agent.agent.Agentrun.id":
		return x.Id != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: agent.agent.Agentrun"))
		}
		panic(fmt.Errorf("message agent.agent.Agentrun does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agentrun) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "agent.agent.Agentrun.query":
		x.Query = ""
	case "agent.agent.Agentrun.responses":
		x.Responses = nil
	case "agent.agent.Agentrun.functioncalls":
		x.Functioncalls = nil
	case "agent.agent.Agentrun.functionresults":
		x.Functionresults = nil
	case "agent.agent.Agentrun.isfinished":
		x.Isfinished = false
	case "agent.agent.Agentrun.id":
		x.Id = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: agent.agent.Agentrun"))
		}
		panic(fmt.Errorf("message agent.agent.Agentrun does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Agentrun) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "agent.agent.Agentrun.query":
		value := x.Query
		return protoreflect.ValueOfString(value)
	case "agent.agent.Agentrun.responses":
		if len(x.Responses) == 0 {
			return protoreflect.ValueOfList(&_Agentrun_2_list{})
		}
		listValue := &_Agentrun_2_list{list: &x.Responses}
		return protoreflect.ValueOfList(listValue)
	case "agent.agent.Agentrun.functioncalls":
		if len(x.Functioncalls) == 0 {
			return protoreflect.ValueOfList(&_Agentrun_3_list{})
		}
		listValue := &_Agentrun_3_list{list: &x.Functioncalls}
		return protoreflect.ValueOfList(listValue)
	case "agent.agent.Agentrun.functionresults":
		if len(x.Functionresults) == 0 {
			return protoreflect.ValueOfList(&_Agentrun_4_list{})
		}
		listValue := &_Agentrun_4_list{list: &x.Functionresults}
		return protoreflect.ValueOfList(listValue)
	case "agent.agent.Agentrun.isfinished":
		value := x.Isfinished
		return protoreflect.ValueOfBool(value)
	case "agent.agent.Agentrun.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: agent.agent.Agentrun"))
		}
		panic(fmt.Errorf("message agent.agent.Agentrun does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agentrun) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "agent.agent.Agentrun.query":
		x.Query = value.Interface().(string)
	case "agent.agent.Agentrun.responses":
		lv := value.List()
		clv := lv.(*_Agentrun_2_list)
		x.Responses = *clv.list
	case "agent.agent.Agentrun.functioncalls":
		lv := value.List()
		clv := lv.(*_Agentrun_3_list)
		x.Functioncalls = *clv.list
	case "agent.agent.Agentrun.functionresults":
		lv := value.List()
		clv := lv.(*_Agentrun_4_list)
		x.Functionresults = *clv.list
	case "agent.agent.Agentrun.isfinished":
		x.Isfinished = value.Bool()
	case "agent.agent.Agentrun.id":
		x.Id = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: agent.agent.Agentrun"))
		}
		panic(fmt.Errorf("message agent.agent.Agentrun does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agentrun) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "agent.agent.Agentrun.responses":
		if x.Responses == nil {
			x.Responses = []string{}
		}
		value := &_Agentrun_2_list{list: &x.Responses}
		return protoreflect.ValueOfList(value)
	case "agent.agent.Agentrun.functioncalls":
		if x.Functioncalls == nil {
			x.Functioncalls = []string{}
		}
		value := &_Agentrun_3_list{list: &x.Functioncalls}
		return protoreflect.ValueOfList(value)
	case "agent.agent.Agentrun.functionresults":
		if x.Functionresults == nil {
			x.Functionresults = []string{}
		}
		value := &_Agentrun_4_list{list: &x.Functionresults}
		return protoreflect.ValueOfList(value)
	case "agent.agent.Agentrun.query":
		panic(fmt.Errorf("field query of message agent.agent.Agentrun is not mutable"))
	case "agent.agent.Agentrun.isfinished":
		panic(fmt.Errorf("field isfinished of message agent.agent.Agentrun is not mutable"))
	case "agent.agent.Agentrun.id":
		panic(fmt.Errorf("field id of message agent.agent.Agentrun is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: agent.agent.Agentrun"))
		}
		panic(fmt.Errorf("message agent.agent.Agentrun does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Agentrun) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "agent.agent.Agentrun.query":
		return protoreflect.ValueOfString("")
	case "agent.agent.Agentrun.responses":
		list := []string{}
		return protoreflect.ValueOfList(&_Agentrun_2_list{list: &list})
	case "agent.agent.Agentrun.functioncalls":
		list := []string{}
		return protoreflect.ValueOfList(&_Agentrun_3_list{list: &list})
	case "agent.agent.Agentrun.functionresults":
		list := []string{}
		return protoreflect.ValueOfList(&_Agentrun_4_list{list: &list})
	case "agent.agent.Agentrun.isfinished":
		return protoreflect.ValueOfBool(false)
	case "agent.agent.Agentrun.id":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: agent.agent.Agentrun"))
		}
		panic(fmt.Errorf("message agent.agent.Agentrun does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Agentrun) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in agent.agent.Agentrun", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Agentrun) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agentrun) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Agentrun) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Agentrun) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Agentrun)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Query)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Responses) > 0 {
			for _, s := range x.Responses {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Functioncalls) > 0 {
			for _, s := range x.Functioncalls {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Functionresults) > 0 {
			for _, s := range x.Functionresults {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.Isfinished {
			n += 2
		}
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Agentrun)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x30
		}
		if x.Isfinished {
			i--
			if x.Isfinished {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x28
		}
		if len(x.Functionresults) > 0 {
			for iNdEx := len(x.Functionresults) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Functionresults[iNdEx])
				copy(dAtA[i:], x.Functionresults[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Functionresults[iNdEx])))
				i--
				dAtA[i] = 0x22
			}
		}
		if len(x.Functioncalls) > 0 {
			for iNdEx := len(x.Functioncalls) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Functioncalls[iNdEx])
				copy(dAtA[i:], x.Functioncalls[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Functioncalls[iNdEx])))
				i--
				dAtA[i] = 0x1a
			}
		}
		if len(x.Responses) > 0 {
			for iNdEx := len(x.Responses) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Responses[iNdEx])
				copy(dAtA[i:], x.Responses[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Responses[iNdEx])))
				i--
				dAtA[i] = 0x12
			}
		}
		if len(x.Query) > 0 {
			i -= len(x.Query)
			copy(dAtA[i:], x.Query)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Query)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Agentrun)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Agentrun: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Agentrun: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Query = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Responses", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Responses = append(x.Responses, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Functioncalls", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Functioncalls = append(x.Functioncalls, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Functionresults", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Functionresults = append(x.Functionresults, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Isfinished", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Isfinished = bool(v != 0)
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: agent/agent/agentrun.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agentrun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query           string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Responses       []string `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	Functioncalls   []string `protobuf:"bytes,3,rep,name=functioncalls,proto3" json:"functioncalls,omitempty"`
	Functionresults []string `protobuf:"bytes,4,rep,name=functionresults,proto3" json:"functionresults,omitempty"`
	Isfinished      bool     `protobuf:"varint,5,opt,name=isfinished,proto3" json:"isfinished,omitempty"`
	Id              uint64   `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Agentrun) Reset() {
	*x = Agentrun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_agent_agentrun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agentrun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agentrun) ProtoMessage() {}

// Deprecated: Use Agentrun.ProtoReflect.Descriptor instead.
func (*Agentrun) Descriptor() ([]byte, []int) {
	return file_agent_agent_agentrun_proto_rawDescGZIP(), []int{0}
}

func (x *Agentrun) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Agentrun) GetResponses() []string {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *Agentrun) GetFunctioncalls() []string {
	if x != nil {
		return x.Functioncalls
	}
	return nil
}

func (x *Agentrun) GetFunctionresults() []string {
	if x != nil {
		return x.Functionresults
	}
	return nil
}

func (x *Agentrun) GetIsfinished() bool {
	if x != nil {
		return x.Isfinished
	}
	return false
}

func (x *Agentrun) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_agent_agent_agentrun_proto protoreflect.FileDescriptor

var file_agent_agent_agentrun_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x72, 0x75, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x63, 0x61, 0x6c, 0x6c, 0x73,
	0x12, 0x28, 0x0a, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x69, 0x73, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x42, 0x8b, 0x01, 0x0a, 0x0f, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x0d,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x72, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x1c, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0xa2, 0x02, 0x03,
	0x41, 0x41, 0x58, 0xaa, 0x02, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0xca, 0x02, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x5c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0xe2,
	0x02, 0x17, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x5c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x3a, 0x3a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_agent_agentrun_proto_rawDescOnce sync.Once
	file_agent_agent_agentrun_proto_rawDescData = file_agent_agent_agentrun_proto_rawDesc
)

func file_agent_agent_agentrun_proto_rawDescGZIP() []byte {
	file_agent_agent_agentrun_proto_rawDescOnce.Do(func() {
		file_agent_agent_agentrun_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_agent_agentrun_proto_rawDescData)
	})
	return file_agent_agent_agentrun_proto_rawDescData
}

var file_agent_agent_agentrun_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agent_agent_agentrun_proto_goTypes = []interface{}{
	(*Agentrun)(nil), // 0: agent.agent.Agentrun
}
var file_agent_agent_agentrun_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_agent_agentrun_proto_init() }
func file_agent_agent_agentrun_proto_init() {
	if File_agent_agent_agentrun_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_agent_agentrun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agentrun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_agent_agentrun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_agent_agentrun_proto_goTypes,
		DependencyIndexes: file_agent_agent_agentrun_proto_depIdxs,
		MessageInfos:      file_agent_agent_agentrun_proto_msgTypes,
	}.Build()
	File_agent_agent_agentrun_proto = out.File
	file_agent_agent_agentrun_proto_rawDesc = nil
	file_agent_agent_agentrun_proto_goTypes = nil
	file_agent_agent_agentrun_proto_depIdxs = nil
}
