// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: agent/agent/tx.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName   = "/agent.agent.Msg/UpdateParams"
	Msg_AskQuestion_FullMethodName    = "/agent.agent.Msg/AskQuestion"
	Msg_AnswerQuestion_FullMethodName = "/agent.agent.Msg/AnswerQuestion"
	Msg_AddPrompt_FullMethodName      = "/agent.agent.Msg/AddPrompt"
	Msg_RunAgent_FullMethodName       = "/agent.agent.Msg/RunAgent"
	Msg_AddResponse_FullMethodName    = "/agent.agent.Msg/AddResponse"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	AskQuestion(ctx context.Context, in *MsgAskQuestion, opts ...grpc.CallOption) (*MsgAskQuestionResponse, error)
	AnswerQuestion(ctx context.Context, in *MsgAnswerQuestion, opts ...grpc.CallOption) (*MsgAnswerQuestionResponse, error)
	AddPrompt(ctx context.Context, in *MsgAddPrompt, opts ...grpc.CallOption) (*MsgAddPromptResponse, error)
	RunAgent(ctx context.Context, in *MsgRunAgent, opts ...grpc.CallOption) (*MsgRunAgentResponse, error)
	AddResponse(ctx context.Context, in *MsgAddResponse, opts ...grpc.CallOption) (*MsgAddResponseResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AskQuestion(ctx context.Context, in *MsgAskQuestion, opts ...grpc.CallOption) (*MsgAskQuestionResponse, error) {
	out := new(MsgAskQuestionResponse)
	err := c.cc.Invoke(ctx, Msg_AskQuestion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AnswerQuestion(ctx context.Context, in *MsgAnswerQuestion, opts ...grpc.CallOption) (*MsgAnswerQuestionResponse, error) {
	out := new(MsgAnswerQuestionResponse)
	err := c.cc.Invoke(ctx, Msg_AnswerQuestion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddPrompt(ctx context.Context, in *MsgAddPrompt, opts ...grpc.CallOption) (*MsgAddPromptResponse, error) {
	out := new(MsgAddPromptResponse)
	err := c.cc.Invoke(ctx, Msg_AddPrompt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RunAgent(ctx context.Context, in *MsgRunAgent, opts ...grpc.CallOption) (*MsgRunAgentResponse, error) {
	out := new(MsgRunAgentResponse)
	err := c.cc.Invoke(ctx, Msg_RunAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddResponse(ctx context.Context, in *MsgAddResponse, opts ...grpc.CallOption) (*MsgAddResponseResponse, error) {
	out := new(MsgAddResponseResponse)
	err := c.cc.Invoke(ctx, Msg_AddResponse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	AskQuestion(context.Context, *MsgAskQuestion) (*MsgAskQuestionResponse, error)
	AnswerQuestion(context.Context, *MsgAnswerQuestion) (*MsgAnswerQuestionResponse, error)
	AddPrompt(context.Context, *MsgAddPrompt) (*MsgAddPromptResponse, error)
	RunAgent(context.Context, *MsgRunAgent) (*MsgRunAgentResponse, error)
	AddResponse(context.Context, *MsgAddResponse) (*MsgAddResponseResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) AskQuestion(context.Context, *MsgAskQuestion) (*MsgAskQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedMsgServer) AnswerQuestion(context.Context, *MsgAnswerQuestion) (*MsgAnswerQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerQuestion not implemented")
}
func (UnimplementedMsgServer) AddPrompt(context.Context, *MsgAddPrompt) (*MsgAddPromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPrompt not implemented")
}
func (UnimplementedMsgServer) RunAgent(context.Context, *MsgRunAgent) (*MsgRunAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAgent not implemented")
}
func (UnimplementedMsgServer) AddResponse(context.Context, *MsgAddResponse) (*MsgAddResponseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddResponse not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAskQuestion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AskQuestion(ctx, req.(*MsgAskQuestion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AnswerQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnswerQuestion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AnswerQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AnswerQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AnswerQuestion(ctx, req.(*MsgAnswerQuestion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddPrompt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddPrompt(ctx, req.(*MsgAddPrompt))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RunAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRunAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RunAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RunAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RunAgent(ctx, req.(*MsgRunAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddResponse(ctx, req.(*MsgAddResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.agent.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "AskQuestion",
			Handler:    _Msg_AskQuestion_Handler,
		},
		{
			MethodName: "AnswerQuestion",
			Handler:    _Msg_AnswerQuestion_Handler,
		},
		{
			MethodName: "AddPrompt",
			Handler:    _Msg_AddPrompt_Handler,
		},
		{
			MethodName: "RunAgent",
			Handler:    _Msg_RunAgent_Handler,
		},
		{
			MethodName: "AddResponse",
			Handler:    _Msg_AddResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/agent/tx.proto",
}
